// Platform-neutral .lunacanvas archive core (W01/W02).
// No PencilKit / UIKit imports — compiled into BOTH the iOS app and the
// macOS fixture generator so the cross-end fixture uses the exact same
// writer as the app (no mirrored logic).

import CryptoKit
import Foundation
import ZIPFoundation

public enum ArchiveLimits {
    // each ink object carries up to 3 entries (drawing/preview/hit), so the
    // entry budget must exceed 3x the ink-object budget; entry metadata is
    // tiny (path + sizes) — the decompression total is the real bomb guard
    public static let maxEntries = 100_000
    public static let maxTotalUncompressedBytes = 512 * 1024 * 1024
    public static let maxSingleEntryBytes = 128 * 1024 * 1024
    // pretty-printed manifest is ~400B per ink object; 20MB supports ~50k
    // objects — real memory is bounded by the decompression total budget
    public static let maxManifestBytes = 20_000_000
    public static let maxEntryPathLength = 512
}

public enum LunaArchiveError: Error {
    case cannotCreateArchive
    case cannotAddEntry(String)
    case invalidManifest(String)
    case missingManifestEntry(String)
    case hashMismatch(String)
    case sizeMismatch(String)
}

public struct LunaArchiveUnit {
    public let objectId: String
    public let data: Data
    public let transform: CGAffineTransform
    /// Rebuildable preview (PNG) and derived hit geometry (JSON). The
    /// drawing is the only irreplaceable payload (N08); previews may be
    /// regenerated by the iPad, so the web treats them as cacheable.
    public let previewData: Data?
    public let hitData: Data?
    public init(
        objectId: String,
        data: Data,
        transform: CGAffineTransform,
        previewData: Data? = nil,
        hitData: Data? = nil,
    ) {
        self.objectId = objectId
        self.data = data
        self.transform = transform
        self.previewData = previewData
        self.hitData = hitData
    }
}

public enum LunaArchive {
    public static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Minimal but REAL scene payload so the manifest passes the TS
    /// contract (0029-R2): an empty (but valid) Excalidraw scene.
    public static func makeEmptySceneData() throws -> Data {
        let scene: [String: Any] = [
            "type": "excalidraw",
            "version": 2,
            "source": "https://excalidraw.com",
            "elements": [],
            "appState": ["viewBackgroundColor": "#ffffff"],
            "files": [:],
        ]
        return try JSONSerialization.data(withJSONObject: scene)
    }

    /// Atomic, transactional save (0029-R5): the archive is fully built in
    /// a temporary file and only then swapped into place; any failure
    /// before the swap leaves the previous file untouched.
    /// Unknown top-level manifest fields are carried through saves so a
    /// newer producer's extensions survive a round-trip (N09 write path).
    public static func export(
        units: [LunaArchiveUnit],
        to url: URL,
        documentId: String,
        revision: Int,
        manifestExtras: [String: Any] = [:],
        preFail: Bool = false,
    ) throws -> Data {
        let fileManager = FileManager()
        let tempURL = url.deletingLastPathComponent()
            .appendingPathComponent(".lunacanvas-tmp-\(UUID().uuidString)")
        do {
            let manifestData = try buildArchive(
                units: units,
                archiveURL: tempURL,
                documentId: documentId,
                revision: revision,
                manifestExtras: manifestExtras,
            )
            if preFail {
                try? fileManager.removeItem(at: tempURL)
                throw LunaArchiveError.cannotCreateArchive
            }
            _ = try fileManager.replaceItemAt(url, withItemAt: tempURL)
            return manifestData
        } catch {
            try? fileManager.removeItem(at: tempURL)
            throw error
        }
    }

    static func buildArchive(
        units: [LunaArchiveUnit],
        archiveURL: URL,
        documentId: String,
        revision: Int,
        manifestExtras: [String: Any] = [:],
    ) throws -> Data {
        let fileManager = FileManager()
        try? fileManager.removeItem(at: archiveURL)
        guard let archive = Archive(url: archiveURL, accessMode: .create) else {
            throw LunaArchiveError.cannotCreateArchive
        }

        var resourceTable: [[String: Any]] = []
        let sceneData = try makeEmptySceneData()
        try addEntry(archive: archive, path: "scene/excalidraw.json", data: sceneData)
        resourceTable.append([
            "path": "scene/excalidraw.json",
            "sha256": sha256Hex(sceneData),
            "byteSize": sceneData.count,
        ])

        for unit in units {
            let hash = sha256Hex(unit.data)
            let path = "ink/\(unit.objectId).drawing"
            try addEntry(archive: archive, path: path, data: unit.data)
            resourceTable.append([
                "path": path,
                "sha256": hash,
                "byteSize": unit.data.count,
            ])
            if let preview = unit.previewData {
                let pPath = "previews/\(unit.objectId).png"
                try addEntry(archive: archive, path: pPath, data: preview)
                resourceTable.append([
                    "path": pPath,
                    "sha256": sha256Hex(preview),
                    "byteSize": preview.count,
                ])
            }
            if let hit = unit.hitData {
                let hPath = "hit/\(unit.objectId).json"
                try addEntry(archive: archive, path: hPath, data: hit)
                resourceTable.append([
                    "path": hPath,
                    "sha256": sha256Hex(hit),
                    "byteSize": hit.count,
                ])
            }
        }

        let inkObjectEntries: [[String: Any]] = units.enumerated().map { index, unit in
            var entry: [String: Any] = [
                "objectId": unit.objectId,
                "nativeAssetRef": "ink/\(unit.objectId).drawing",
                "worldTransform": [
                    unit.transform.a, unit.transform.b, unit.transform.c,
                    unit.transform.d, unit.transform.tx, unit.transform.ty,
                ],
                "order": index,
                "contentVersion": 1,
                "contentHash": sha256Hex(unit.data),
            ]
            if unit.previewData != nil {
                entry["previewRef"] = "previews/\(unit.objectId).png"
            }
            if unit.hitData != nil {
                entry["hitGeometryRef"] = "hit/\(unit.objectId).json"
            }
            return entry
        }
        let manifest: [String: Any] = [
            "type": "lunacanvas",
            "schemaVersion": 1,
            "documentId": documentId,
            "revision": revision,
            "capabilities": ["ink", "graphics"],
            "sceneRef": "scene/excalidraw.json",
            "layerStrategy": "ink-above-graphics",
            "inkObjects": inkObjectEntries,
            "resources": resourceTable,
        ].merging(manifestExtras) { current, _ in current }
        let manifestData = try JSONSerialization.data(
            withJSONObject: manifest,
            options: [.prettyPrinted, .sortedKeys],
        )
        try addEntry(archive: archive, path: "manifest.json", data: manifestData)
        return manifestData
    }

    /// Normalized container-relative path rules — mirror of the TS
    /// isSafeContainerPath (W02); keep in sync with container.ts.
    public static func isSafeContainerPath(_ path: String) -> Bool {
        if path.isEmpty || path.count > ArchiveLimits.maxEntryPathLength {
            return false
        }
        if path.contains("\\") || path.contains("\0") {
            return false
        }
        if path.hasPrefix("/") {
            return false
        }
        // URLs (any scheme://)
        if let range = path.range(of: "://") {
            let scheme = path[..<range.lowerBound]
            if !scheme.isEmpty && scheme.allSatisfy({ $0.isLetter || $0.isNumber || $0 == "+" || $0 == "-" || $0 == "." }) {
                return false
            }
        }
        // drive letters (C: etc.)
        if path.count >= 2, path[path.index(path.startIndex, offsetBy: 1)] == ":" {
            return false
        }
        return !path.split(separator: "/").contains("..")
    }

    /// Strict reading: malformed manifests throw, never degrade into an
    /// empty document (0029-R3). Envelope budgets are enforced from entry
    /// metadata BEFORE any payload is extracted (W02). Returns (documentId,
    /// revision, sceneData, units) with each unit's raw bytes preserved.
    public static func open(
        url: URL,
    ) throws -> (
        documentId: String,
        revision: Int,
        sceneData: Data,
        units: [LunaArchiveUnit],
        orders: [Int],
        /// unknown top-level fields, for write-path preservation (N09)
        manifestExtras: [String: Any],
    ) {
        guard let archive = Archive(url: url, accessMode: .read) else {
            throw LunaArchiveError.cannotCreateArchive
        }

        // envelope validation from metadata only (no extraction yet)
        var seenPaths = Set<String>()
        var totalUncompressed: UInt64 = 0
        var manifestEntrySize: Int?
        var entryCount = 0
        var entryByPath: [String: Entry] = [:]
        for entry in archive {
            entryCount += 1
            entryByPath[entry.path] = entry
            guard isSafeContainerPath(entry.path) else {
                throw LunaArchiveError.invalidManifest("unsafe entry path \(entry.path)")
            }
            guard !seenPaths.contains(entry.path) else {
                throw LunaArchiveError.invalidManifest("duplicate entry path \(entry.path)")
            }
            seenPaths.insert(entry.path)
            totalUncompressed += UInt64(entry.uncompressedSize)
            if entry.path == "manifest.json" {
                manifestEntrySize = Int(entry.uncompressedSize)
            }
        }
        guard entryCount <= ArchiveLimits.maxEntries else {
            throw LunaArchiveError.invalidManifest("too many entries")
        }
        guard totalUncompressed <= UInt64(ArchiveLimits.maxTotalUncompressedBytes) else {
            throw LunaArchiveError.invalidManifest("decompressed total exceeds budget")
        }
        if let manifestEntrySize, manifestEntrySize > ArchiveLimits.maxManifestBytes {
            throw LunaArchiveError.invalidManifest("manifest.json exceeds budget")
        }

        func entryData(_ path: String) throws -> Data {
            guard let entry = entryByPath[path] else {
                throw LunaArchiveError.missingManifestEntry(path)
            }
            var data = Data()
            _ = try archive.extract(entry) { chunk in
                data.append(chunk)
            }
            return data
        }

        let manifestData = try entryData("manifest.json")
        let parsed: Any
        do {
            parsed = try JSONSerialization.jsonObject(with: manifestData)
        } catch {
            throw LunaArchiveError.invalidManifest("manifest is not valid JSON")
        }
        guard let manifest = parsed as? [String: Any] else {
            throw LunaArchiveError.invalidManifest("manifest is not an object")
        }
        guard manifest["type"] as? String == "lunacanvas" else {
            throw LunaArchiveError.invalidManifest("bad type")
        }
        guard manifest["schemaVersion"] as? Int == 1 else {
            throw LunaArchiveError.invalidManifest("unsupported schemaVersion")
        }
        guard let documentId = manifest["documentId"] as? String, !documentId.isEmpty
        else {
            throw LunaArchiveError.invalidManifest("documentId required")
        }
        guard let revision = manifest["revision"] as? Int, revision >= 0 else {
            throw LunaArchiveError.invalidManifest("revision must be a non-negative integer")
        }
        guard let capabilities = manifest["capabilities"] as? [String] else {
            throw LunaArchiveError.invalidManifest("capabilities must be a string array")
        }
        guard capabilities.allSatisfy({ !$0.isEmpty }) else {
            throw LunaArchiveError.invalidManifest("empty capability string")
        }
        guard manifest["layerStrategy"] as? String == "ink-above-graphics" else {
            throw LunaArchiveError.invalidManifest("unknown layerStrategy")
        }
        guard let inkObjects = manifest["inkObjects"] as? [[String: Any]] else {
            throw LunaArchiveError.invalidManifest("inkObjects must be an array of objects")
        }

        let resources = manifest["resources"] as? [[String: Any]] ?? []
        let resourceByPath = Dictionary(
            resources.compactMap { entry -> (String, [String: Any])? in
                guard let path = entry["path"] as? String else { return nil }
                return (path, entry)
            },
            uniquingKeysWith: { first, _ in first },
        )

        let sceneRef = manifest["sceneRef"] as? String ?? "scene/excalidraw.json"
        let sceneData = try entryData(sceneRef)

        let knownKeys: Set<String> = [
            "type", "schemaVersion", "documentId", "revision", "capabilities",
            "sceneRef", "layerStrategy", "inkObjects", "resources",
        ]
        let manifestExtras = manifest.filter { !knownKeys.contains($0.key) }

        var seenObjectIds = Set<String>()
        var units: [LunaArchiveUnit] = []
        var orders: [Int] = []
        for entry in inkObjects {
            guard
                let objectId = entry["objectId"] as? String,
                !objectId.isEmpty
            else {
                throw LunaArchiveError.invalidManifest("inkObject missing objectId")
            }
            guard !seenObjectIds.contains(objectId) else {
                throw LunaArchiveError.invalidManifest("duplicate objectId \(objectId)")
            }
            seenObjectIds.insert(objectId)

            guard let ref = entry["nativeAssetRef"] as? String else {
                throw LunaArchiveError.invalidManifest("inkObject missing nativeAssetRef")
            }
            guard
                let resource = resourceByPath[ref],
                let expectedHash = resource["sha256"] as? String,
                let expectedSize = resource["byteSize"] as? Int
            else {
                throw LunaArchiveError.invalidManifest("ref \(ref) missing from resources")
            }
            guard
                let expectedContentHash = entry["contentHash"] as? String
            else {
                throw LunaArchiveError.invalidManifest("inkObject missing contentHash")
            }
            guard
                let t = entry["worldTransform"] as? [Double],
                t.count == 6,
                t.allSatisfy({ $0.isFinite })
            else {
                throw LunaArchiveError.invalidManifest("bad worldTransform")
            }
            guard
                let order = entry["order"] as? Int,
                order >= 0
            else {
                throw LunaArchiveError.invalidManifest("bad order")
            }

            let data = try entryData(ref)
            guard data.count == expectedSize else {
                throw LunaArchiveError.sizeMismatch(ref)
            }
            let actualHash = sha256Hex(data)
            guard
                actualHash.caseInsensitiveCompare(expectedHash) == .orderedSame,
                actualHash.caseInsensitiveCompare(expectedContentHash) == .orderedSame
            else {
                throw LunaArchiveError.hashMismatch(ref)
            }

            func optionalRef(_ key: String) throws -> Data? {
                guard let ref = entry[key] as? String else { return nil }
                return try entryData(ref)
            }
            units.append(
                LunaArchiveUnit(
                    objectId: objectId,
                    data: data,
                    transform: CGAffineTransform(
                        a: t[0], b: t[1], c: t[2], d: t[3], tx: t[4], ty: t[5]
                    ),
                    previewData: try optionalRef("previewRef"),
                    hitData: try optionalRef("hitGeometryRef"),
                )
            )
            orders.append(order)
        }

        let combined = zip(units, orders).sorted { $0.1 < $1.1 }
        return (
            documentId,
            revision,
            sceneData,
            combined.map(\.0),
            combined.map(\.1),
            manifestExtras,
        )
    }

    static func addEntry(
        archive: Archive,
        path: String,
        data: Data,
    ) throws {
        do {
            try archive.addEntry(
                with: path,
                type: .file,
                uncompressedSize: UInt32(data.count),
                compressionMethod: .deflate,
            ) { position, size -> Data in
                data.subdata(in: position..<min(position + size, data.count))
            }
        } catch {
            throw LunaArchiveError.cannotAddEntry(
                "\(path): \(error.localizedDescription)",
            )
        }
    }
}
